version: '3.9'

services:
  backend:
    build:
      context: ./url_shortener
      dockerfile: Dockerfile
    volumes:
      - ./url_shortener:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SUPERUSER_USERNAME=admin1
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/app
    ports:
      - "5173:5173"