version: '3.8'

services:
  backend:
    build: ./url_shortener
    container_name: backend
    environment:
      DJANGO_SUPERUSER_USERNAME: admin1
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    volumes:
      - ./url_shortener:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:5173" 
