# Generated by Django 5.1.1 on 2024-09-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
